### ISSUE TITLE
Convert Nim.py from Python 2.7 to Python3

### ISSUE THREAD

**Issue by ashwanijha04** [ashwanijha04/Python-mini-projects#2]
Convert the Nim.py game from Python2.7 to Python3.

**Comment by piyushjha7** [comment]
I want to work on it. Can you please assign it to me

**Comment by ashwanijha04** [comment]
Sure, assigning it to you. Thanks for your help and supporting the project for beginners.

**Comment by ashwanijha04** [comment]
Merged as part of https://github.com/ashwanijha04/Python-mini-projects/pull/3

Thanks for the help.

Closing...
