### ISSUE TITLE
Convert TicTacToe from Python2.7 to Python3

### ISSUE THREAD

**Issue by ashwanijha04** [ashwanijha04/Python-mini-projects#5]
The TicTacToe file is old and is written in Python2.7
Need help in updating the repository to Python3.

**Comment by RascalTwo** [comment]
I can do this

**Comment by yashqwerty1** [comment]
Can You assign this to me?

**Comment by RascalTwo** [comment]
Looks like we were both beat to this one - #6 :laughing:

**Comment by yashqwerty1** [comment]
Yup You can go ahead man Next time is mine

**Comment by adripo** [comment]
Can you add the "hacktoberfest" topic in your project's About please, so the pr is elegible to hacktoberfest?

**Comment by piyushjha7** [comment]
Please assign this to me.
